// <auto-generated />
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations.Hobbies
{
    [DbContext(typeof(HobbiesContext))]
    [Migration("20221203050213_FinalMigrations")]
    partial class FinalMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProject.Models.Hobby", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_id"), 1L, 1);

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobby_Name1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobby_Name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hours_Spent1")
                        .HasColumnType("int");

                    b.Property<int>("Hours_Spent2")
                        .HasColumnType("int");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_id");

                    b.ToTable("Hobby");

                    b.HasData(
                        new
                        {
                            User_id = 1,
                            First_Name = "Joshua",
                            Hobby_Name1 = "FL Studio",
                            Hobby_Name2 = "Fixing Computers",
                            Hours_Spent1 = 1435,
                            Hours_Spent2 = 500,
                            Last_Name = "Chapman"
                        },
                        new
                        {
                            User_id = 2,
                            First_Name = "Tigran",
                            Hobby_Name1 = "Playing Games",
                            Hobby_Name2 = "Working out",
                            Hours_Spent1 = 3000,
                            Hours_Spent2 = 85,
                            Last_Name = "Klekchyan"
                        },
                        new
                        {
                            User_id = 3,
                            First_Name = "Andrew",
                            Hobby_Name1 = "Playing Cards",
                            Hobby_Name2 = "Playing Games",
                            Hours_Spent1 = 1500,
                            Hours_Spent2 = 1370,
                            Last_Name = "Iverson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
